name = "psw-qwen-ai"
type = "javascript"

account_id = "deab1848c77408b182c391e586116d9f"
workers_dev = true
# Uncomment and set these if you are deploying to a custom domain.
# route = "https://your-custom-domain.com/*"
# zone_id = "your-zone-id"